/* ═══════════════════════════════════════════════════════════
   CHEMSPHERE — moleculeData.js
   MOLECULE DATABASE & CORE STATE
   Static DB of all molecules (VSEPR, organic, inorganic, biomolecules) plus the core viewer/rotation state variables.
═══════════════════════════════════════════════════════════ */

/* ════════════════════════════════════════
   MOLECULE DATABASE
   Key = used for DB lookup + grid
   pname = sent to NCI Cactus API (plain English)
════════════════════════════════════════ */
const DB = {
  vsepr: [
    {key:'vsepr-h2o',  pname:'water',                    f:'H₂O',   n:'Water',                   s:'Bent',              w:'18.02', h:'sp³',   a:'104.5°', d:'1.85 D', g:'Bent / V-Shape — 2 lone pairs on O reduce bond angle below 109.5°',      x:'Bond angle 104.5° (not 109.5°) due to lone pair–bond pair repulsion. Most common NEET VSEPR question.'},
    {key:'vsepr-co2',  pname:'carbon dioxide',            f:'CO₂',   n:'Carbon Dioxide',          s:'Linear',            w:'44.01', h:'sp',    a:'180°',   d:'0 D',    g:'Linear — symmetric, 2 C=O bonds, no lone pairs on C',                    x:'ZERO net dipole despite polar C=O bonds — symmetry causes cancellation. Classic NEET trap!'},
    {key:'vsepr-bf3',  pname:'boron trifluoride',         f:'BF₃',   n:'Boron Trifluoride',       s:'Trigonal Planar',   w:'67.81', h:'sp²',   a:'120°',   d:'0 D',    g:'Trigonal Planar — sp², empty p-orbital on B (Lewis acid)',                x:'BF₃ is a strong Lewis acid. Its empty p-orbital accepts lone pairs. Dipole = 0 (symmetric).'},
    {key:'vsepr-ch4',  pname:'methane',                   f:'CH₄',   n:'Methane',                 s:'Tetrahedral',       w:'16.04', h:'sp³',   a:'109.5°', d:'0 D',    g:'Tetrahedral — perfect symmetry, all 4 bond pairs equivalent',             x:'All bonds equivalent by symmetry → dipole = 0. The ideal tetrahedral reference molecule.'},
    {key:'vsepr-nh3',  pname:'ammonia',                   f:'NH₃',   n:'Ammonia',                 s:'Pyramidal',         w:'17.03', h:'sp³',   a:'107°',   d:'1.47 D', g:'Trigonal Pyramidal — 1 lone pair on N lowers angle to 107°',              x:'NH₃ is a Lewis base & Brønsted base. Lone pair on N is key for H-bond donation & nucleophilicity.'},
    {key:'vsepr-pcl5', pname:'phosphorus pentachloride',  f:'PCl₅',  n:'PCl₅',                    s:'Trig. Bipyramidal', w:'208.2', h:'sp³d',  a:'90°/120°',d:'0 D',   g:'Trigonal Bipyramidal — axial bonds longer than equatorial',               x:'Axial bonds (240 pm) > equatorial bonds (202 pm). Expanded octet on P. JEE Advanced level.'},
    {key:'vsepr-sf6',  pname:'sulfur hexafluoride',       f:'SF₆',   n:'Sulfur Hexafluoride',     s:'Octahedral',        w:'146.1', h:'sp³d²', a:'90°',    d:'0 D',    g:'Octahedral — sp³d², all 90° bond angles, no lone pairs',                 x:'SF₆ is a greenhouse gas 23,500× more potent than CO₂. Inert due to perfect octahedral symmetry.'},
    {key:'vsepr-xef4', pname:'xenon tetrafluoride',       f:'XeF₄',  n:'Xenon Tetrafluoride',     s:'Square Planar',     w:'207.3', h:'sp³d²', a:'90°',    d:'0 D',    g:'Square Planar — 2 lone pairs sit opposite (trans) each other',            x:'6 electron pairs (sp³d²) but 2 lone pairs cancel → Square Planar. Key JEE distinction.'},
  ],
  organic: [
    {key:'org-benz',   pname:'benzene',      f:'C₆H₆',    n:'Benzene',      s:'Hexagonal',       w:'78.11', h:'sp²', a:'120°',   d:'0 D',    g:'Planar hexagonal ring — resonance stabilized, delocalized π electrons', x:'6 equivalent C-C bonds via resonance. Aromatic (Hückel: 4n+2, n=1). Dipole = 0.'},
    {key:'org-etoh',   pname:'ethanol',      f:'C₂H₅OH',  n:'Ethanol',      s:'Tetrahedral C',   w:'46.07', h:'sp³', a:'109.5°', d:'1.69 D', g:'Tetrahedral C atoms; bent O (H-bond donor, –OH group)',                x:'–OH forms H-bonds → fully miscible in water. Bp 78°C >> propane –42°C, similar MW.'},
    {key:'org-acet',   pname:'acetone',      f:'C₃H₆O',   n:'Acetone',      s:'Trigonal Planar', w:'58.08', h:'sp²', a:'~120°',  d:'2.91 D', g:'Trigonal planar at carbonyl C (sp²) — C=O double bond',                x:'Ketone (propanone). Most polar common solvent without H-bond donation. Nail polish remover.'},
    {key:'org-acac',   pname:'acetic acid',  f:'CH₃COOH', n:'Acetic Acid',  s:'Planar –COOH',    w:'60.05', h:'sp²', a:'~120°',  d:'1.74 D', g:'Planar –COOH group; sp² carbonyl carbon with resonance',               x:'Forms H-bonded DIMERS in nonpolar solvents → apparent MW ~120 g/mol. Classic JEE concept.'},
    {key:'org-form',   pname:'formaldehyde', f:'CH₂O',    n:'Formaldehyde', s:'Trigonal Planar', w:'30.03', h:'sp²', a:'~120°',  d:'2.33 D', g:'Trigonal planar (sp²) — simplest aldehyde, C=O double bond',           x:'Formalin (37% aq.) = preservative. Reacts with NaHSO₃ → bisulfite addition product.'},
  ],
  biomol: [
    {key:'bio-gluc',   pname:'glucose',      f:'C₆H₁₂O₆', n:'Glucose',     s:'Pyranose Ring',   w:'180.2', h:'sp³', a:'109.5°', d:'—', g:'Pyranose ring — 6-membered; chair conformation, all sp³ C',               x:'α-glucose (36%) and β-glucose (64%) in solution — mutarotation. D-glucose is dextrorotatory.'},
    {key:'bio-aden',   pname:'adenine',      f:'C₅H₅N₅',  n:'Adenine',     s:'Planar Bicyclic', w:'135.1', h:'sp²', a:'~120°',  d:'—', g:'Planar purine — bicyclic aromatic (sp² N and C atoms)',                    x:'Pairs with Thymine via 2 H-bonds in DNA; Uracil in RNA. Component of ATP.'},
    {key:'bio-chol',   pname:'cholesterol',  f:'C₂₇H₄₆O', n:'Cholesterol', s:'Steroid Core',    w:'386.7', h:'sp³', a:'109.5°', d:'—', g:'Four fused rings (steroid skeleton) — mostly sp³ carbons',                 x:'Precursor to Vitamin D, bile acids & steroid hormones. Transported by LDL (bad cholesterol).'},
    {key:'bio-alan',   pname:'alanine',      f:'C₃H₇NO₂', n:'Alanine',     s:'Tetrahedral',     w:'89.09', h:'sp³', a:'109.5°', d:'—', g:'Tetrahedral α-carbon (sp³) — simplest chiral amino acid',                  x:'Simplest chiral (L-config) amino acid. R-group = –CH₃. Non-essential amino acid.'},
  ],
  inorganic: [
    {key:'in-h2so4',   pname:'sulfuric acid',         f:'H₂SO₄',  n:'Sulfuric Acid',        s:'Tetrahedral',       w:'98.08', h:'sp³',   a:'109.5°',  d:'—',      g:'Tetrahedral around S — sp³, two S=O and two S–OH bonds',                   x:'Conc. H₂SO₄ = strong dehydrating & oxidising agent. ALWAYS add acid to water!'},
    {key:'in-hno3',    pname:'nitric acid',           f:'HNO₃',   n:'Nitric Acid',          s:'Trigonal Planar',   w:'63.01', h:'sp²',   a:'~120°',   d:'—',      g:'Trigonal planar around N (sp²) — resonance in NO₃⁻',                       x:'HNO₃ + conc. HCl (1:3) = Aqua Regia — dissolves gold & platinum. Brown ring test for NO₃⁻.'},
    {key:'in-nh3',     pname:'ammonia',               f:'NH₃',    n:'Ammonia',              s:'Pyramidal',         w:'17.03', h:'sp³',   a:'107°',    d:'1.47 D', g:'Trigonal Pyramidal — 1 lone pair on N',                                     x:'Haber Process: N₂ + 3H₂ ⇌ 2NH₃ (Fe catalyst, ~500°C, ~200 atm). Le Chatelier principle.'},
    {key:'in-h3po4',   pname:'phosphoric acid',       f:'H₃PO₄',  n:'Phosphoric Acid',      s:'Tetrahedral',       w:'98.0',  h:'sp³',   a:'~109.5°', d:'—',      g:'Tetrahedral around P — sp³ hybridised phosphorus',                         x:'Triprotic acid (Ka1>>Ka2>>Ka3). Phosphodiester bonds in DNA/RNA backbone.'},
    {key:'in-hf',      pname:'hydrogen fluoride',     f:'HF',     n:'Hydrogen Fluoride',    s:'Linear',            w:'20.01', h:'sp³',   a:'—',       d:'1.82 D', g:'Linear diatomic — strongest H-bond donor among haloacids',                  x:'HF is a weak acid (Ka=6.8×10⁻⁴) despite F being most electronegative — H-bond network resists ionisation. Etches glass via SiO₂ + 4HF → SiF₄.'},
    {key:'in-hcl',     pname:'hydrogen chloride',     f:'HCl',    n:'Hydrogen Chloride',    s:'Linear',            w:'36.46', h:'sp³',   a:'—',       d:'1.08 D', g:'Linear diatomic — polar covalent bond, strong acid in water',               x:'HCl is a strong acid (fully ionised in water). Bond polarity: δ+H–Clδ−. Stronger acid than HF despite lower electronegativity of Cl — HF resists ionisation due to H-bonding.'},
    {key:'in-becl2',   pname:'beryllium chloride',    f:'BeCl₂',  n:'Beryllium Chloride',   s:'Linear',            w:'79.91', h:'sp',    a:'180°',    d:'0 D',    g:'Linear — sp hybridised Be, no lone pairs, only 2 bond pairs',               x:'BeCl₂ is electron deficient (only 4 electrons around Be). Acts as Lewis acid. In solid state forms polymeric chain via Cl lone pair bridges.'},
    {key:'in-nf3',     pname:'nitrogen trifluoride',  f:'NF₃',    n:'Nitrogen Trifluoride', s:'Pyramidal',         w:'71.0',  h:'sp³',   a:'102.5°',  d:'0.24 D', g:'Trigonal Pyramidal — like NH₃ but F pulls e-density away from N',           x:'NF₃ bond angle 102.5° < NH₃ 107° — F pulls electron density away, reducing lone pair repulsion. Classic NEET comparison with NH₃.'},
    {key:'in-of2',     pname:'oxygen difluoride',     f:'OF₂',    n:'Oxygen Difluoride',    s:'Bent',              w:'54.0',  h:'sp³',   a:'102°',    d:'0.30 D', g:'Bent — 2 lone pairs on O, F pulls e-density reducing angle to 102°',        x:'OF₂ bond angle 102° < H₂O 104.5° — F more electronegative than H, pulls bonding pairs further from O. Unusual: O oxidation state = +2 here.'},
    {key:'in-clf3',    pname:'chlorine trifluoride',  f:'ClF₃',   n:'Chlorine Trifluoride', s:'T-shaped',          w:'92.45', h:'sp³d',  a:'87.5°',   d:'0.6 D',  g:'T-shaped — 5 electron pairs (sp³d), 2 lone pairs equatorial',               x:'ClF₃ is T-shaped NOT trigonal planar — lone pairs occupy equatorial positions (less repulsion). Angle 87.5° < 90° due to lone pair compression. Key JEE Advanced question.'},
    {key:'in-xef2',    pname:'xenon difluoride',      f:'XeF₂',   n:'Xenon Difluoride',     s:'Linear',            w:'169.3', h:'sp³d',  a:'180°',    d:'0 D',    g:'Linear — 5 electron pairs (sp³d), 3 lone pairs equatorial, 2 F axial',      x:'XeF₂ linear: 3 lone pairs arrange equatorially, F atoms axially. First noble gas compound (1962). Used in semiconductor etching.'},
    {key:'in-so2',     pname:'sulfur dioxide',        f:'SO₂',    n:'Sulfur Dioxide',       s:'Bent',              w:'64.06', h:'sp²',   a:'119°',    d:'1.63 D', g:'Bent — sp² S with 1 lone pair, resonance between S=O bonds',               x:'SO₂ resonance: both S–O bonds equal (143 pm). Cause of acid rain. Bleaching agent — decolourises litmus (not permanent like Cl₂).'},
    {key:'in-so3',     pname:'sulfur trioxide',       f:'SO₃',    n:'Sulfur Trioxide',      s:'Trigonal Planar',   w:'80.06', h:'sp²',   a:'120°',    d:'0 D',    g:'Trigonal Planar — sp² S, 3 equivalent S–O bonds via resonance',             x:'SO₃ + H₂O → H₂SO₄. Contact process: 2SO₂ + O₂ ⇌ 2SO₃ (V₂O₅ catalyst). Dipole = 0 despite polar bonds — symmetry cancels them.'},
    {key:'in-pcl3',    pname:'phosphorus trichloride',f:'PCl₃',   n:'PCl₃',                 s:'Pyramidal',         w:'137.3', h:'sp³',   a:'100°',    d:'0.97 D', g:'Trigonal Pyramidal — 1 lone pair on P, angle 100°',                        x:'PCl₃ angle 100° < NH₃ 107° — P larger atom, lone pair less compact. Reacts with water: PCl₃ + 3H₂O → H₃PO₃ + 3HCl.'},
    {key:'in-no2',     pname:'nitrogen dioxide',      f:'NO₂',    n:'Nitrogen Dioxide',     s:'Bent',              w:'46.01', h:'sp²',   a:'134°',    d:'0.32 D', g:'Bent — sp², 1 unpaired electron on N (radical), angle 134°',               x:'NO₂ angle 134° > 120° — unpaired electron takes less space than lone pair. Brown fumes. Dimerises → N₂O₄. JEE: odd-electron molecule.'},
    {key:'in-o3',      pname:'ozone',                 f:'O₃',     n:'Ozone',                s:'Bent',              w:'48.0',  h:'sp²',   a:'117°',    d:'0.53 D', g:'Bent — sp² central O, resonance between two O–O bonds',                    x:'O₃ resonance: equal O–O bonds (128 pm). Absorbs UV in stratosphere. Starch-iodide paper turns blue in presence of O₃. Stronger oxidiser than O₂.'},
    {key:'in-h2o2',    pname:'hydrogen peroxide',     f:'H₂O₂',  n:'Hydrogen Peroxide',    s:'Non-planar Bent',   w:'34.01', h:'sp³',   a:'111°',    d:'2.26 D', g:'Non-planar — dihedral angle ~112°, O–O single bond, 2 lone pairs per O',   x:'H₂O₂ is both oxidiser AND reducer. Decomposes: 2H₂O₂ → 2H₂O + O₂ (MnO₂ catalyst). Oxidation state of O = –1 (unusual — between 0 and –2).'},
    {key:'in-n2o',     pname:'nitrous oxide',         f:'N₂O',    n:'Nitrous Oxide',        s:'Linear',            w:'44.01', h:'sp',    a:'180°',    d:'0.17 D', g:'Linear — sp, resonance N=N=O and N≡N–O structures',                       x:'N₂O (laughing gas) — anaesthetic & greenhouse gas (300× CO₂ potency). Asymmetric linear → non-zero dipole despite linearity. JEE: distinguish from CO₂ (symmetric, dipole=0).'},
    {key:'in-diborane',pname:'diborane',              f:'B₂H₆',   n:'Diborane',             s:'Bridged',           w:'27.67', h:'sp³',   a:'97°',     d:'0 D',    g:'Banana bonds — 2 bridging H shared between B via 3-centre 2-electron bonds', x:'B₂H₆ three-centre two-electron bonds — electron deficient. No lone pairs yet acts as Lewis acid. B₂H₆ + 6H₂O → 2B(OH)₃ + 6H₂. Key JEE structure.'},
    {key:'in-ph3',     pname:'phosphine',             f:'PH₃',    n:'Phosphine',            s:'Pyramidal',         w:'34.0',  h:'sp³',   a:'93.5°',   d:'0.58 D', g:'Trigonal Pyramidal — lone pair on P, angle 93.5° (near 90°)',               x:'PH₃ angle 93.5° ≈ 90° — P uses nearly pure p-orbitals. Much weaker base than NH₃ — lone pair in large diffuse orbital. Compare: NH₃ 107°, PH₃ 93.5°, AsH₃ 91.8°.'},
    {key:'in-carbonic',pname:'carbonic acid',         f:'H₂CO₃',  n:'Carbonic Acid',        s:'Trigonal Planar',   w:'62.03', h:'sp²',   a:'120°',    d:'—',      g:'Trigonal planar around C (sp²) — 3 groups around carbonyl carbon',         x:'CO₂ + H₂O ⇌ H₂CO₃. Diprotic weak acid. Carbonate buffer (pH 7.35–7.45) regulates blood pH — crucial NEET Biology + Chemistry crossover.'},
  ],
  organic2: [
    {key:'org-eth',    pname:'ethene',               f:'C₂H₄',   n:'Ethene',               s:'Trigonal Planar',   w:'28.05', h:'sp²',   a:'120°',    d:'0 D',    g:'Trigonal planar — sp² carbons, C=C (σ + π bond)',                          x:'C=C π bond prevents rotation → cis/trans isomers. Ethene is plant hormone (fruit ripening). Br₂ decolourisation = unsaturation test. Addition polymerisation → polyethylene.'},
    {key:'org-ethy',   pname:'ethyne',               f:'C₂H₂',   n:'Ethyne',               s:'Linear',            w:'26.04', h:'sp',    a:'180°',    d:'0 D',    g:'Linear — sp carbons, C≡C triple bond (σ + 2π bonds)',                      x:'C≡C: sp hybridised, linear. Terminal H is acidic (pKa~25) — reacts Na → sodium acetylide. Oxyacetylene flame 3500°C. Markovnikov addition with HBr → CH₃CHBr₂.'},
    {key:'org-chloro', pname:'chloroform',           f:'CHCl₃',  n:'Chloroform',           s:'Tetrahedral',       w:'119.4', h:'sp³',   a:'~109.5°', d:'1.15 D', g:'Tetrahedral C — 3 Cl atoms pull e-density, giving net dipole',              x:'CHCl₃ was first anaesthetic (1847). Iodoform test: CHI₃ yellow ppt identifies CH₃CO– group (methyl ketones, ethanol). Reacts NaOH → dichlorocarbene.'},
    {key:'org-ccl4',   pname:'carbon tetrachloride', f:'CCl₄',   n:'Carbon Tetrachloride', s:'Tetrahedral',       w:'153.8', h:'sp³',   a:'109.5°',  d:'0 D',    g:'Tetrahedral — 4 identical C–Cl bonds, perfect symmetry → dipole = 0',      x:'CCl₄ dipole = 0 despite 4 polar C–Cl bonds — symmetry cancels all. Classic NEET MCQ. Compare with CHCl₃ (dipole ≠ 0). Ozone-depleting substance.'},
    {key:'org-urea',   pname:'urea',                 f:'CO(NH₂)₂',n:'Urea',               s:'Trigonal Planar',   w:'60.06', h:'sp²',   a:'~120°',   d:'4.56 D', g:'Trigonal planar carbonyl C (sp²) — resonance across N–C=O',               x:'First organic compound from inorganic source (Wöhler 1828) — disproved vitalism. Nitrogenous waste in mammals. Fertiliser (46% N). Denaturation of proteins at high concentration.'},
  ]
};

/* ════════════════════════════════════════
   STATE
════════════════════════════════════════ */
let viewer = null, model = null;
let rotating = true;

